// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEe_1y81zRHnZf7r0C8xfaTQw_Oy6e9TQ',
    appId: '1:410695498942:web:4bd9284c9d71ba397ef2ef',
    messagingSenderId: '410695498942',
    projectId: 'flutter-ddd97',
    authDomain: 'flutter-ddd97.firebaseapp.com',
    storageBucket: 'flutter-ddd97.firebasestorage.app',
    measurementId: 'G-SZNR600QJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu971BiW45tP6m40mHAiaJExkTcZ25uj0',
    appId: '1:410695498942:android:05e3a2c688db7b577ef2ef',
    messagingSenderId: '410695498942',
    projectId: 'flutter-ddd97',
    storageBucket: 'flutter-ddd97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwnpCLzu7xlJu3gDuygl-SFw7L9XqC7QY',
    appId: '1:410695498942:ios:6b59209d6e5bead47ef2ef',
    messagingSenderId: '410695498942',
    projectId: 'flutter-ddd97',
    storageBucket: 'flutter-ddd97.firebasestorage.app',
    iosBundleId: 'com.example.aiStudyAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwnpCLzu7xlJu3gDuygl-SFw7L9XqC7QY',
    appId: '1:410695498942:ios:6b59209d6e5bead47ef2ef',
    messagingSenderId: '410695498942',
    projectId: 'flutter-ddd97',
    storageBucket: 'flutter-ddd97.firebasestorage.app',
    iosBundleId: 'com.example.aiStudyAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEe_1y81zRHnZf7r0C8xfaTQw_Oy6e9TQ',
    appId: '1:410695498942:web:d1b7a14cbedcc0b97ef2ef',
    messagingSenderId: '410695498942',
    projectId: 'flutter-ddd97',
    authDomain: 'flutter-ddd97.firebaseapp.com',
    storageBucket: 'flutter-ddd97.firebasestorage.app',
    measurementId: 'G-2JMVKTTCKY',
  );
}
